name: ChatLink CI/CD Pipeline

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest

    steps: 
    # Step 1: Checkout the repo code
    - name: Checkout Code
      uses: actions/checkout@v3

    # Step 2: Log into Docker Hub
    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with: 
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    # Step 3: Install Docker Compose
    - name: Install Docker Compose
      run: |
        sudo apt-get update
        sudo apt-get install -y docker-compose

    # Step 4: Build and Push Docker Images to Docker Hub
    - name: Build and Push Docker Images
      run: |
        docker-compose -f docker-compose.yml build
        docker-compose -f docker-compose.yml push 

    # Step 5: Copy docker-compose.yml and nginx directory to EC2
    - name: Copy Files to EC2
      uses: appleboy/scp-action@v0.1.5
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
        source: |
          docker-compose.yml
        target: ~/chatlink/
        debug: true

    # Step 6: Deploy the Application on the EC2 Instance
    - name: Deploy to EC2
      uses: appleboy/ssh-action@v0.1.7
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
        script: |
          cd ~/chatlink
          docker-compose pull
          docker-compose down
          docker-compose up -d

