name: ChatLink CI/CD Pipeline

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest


    steps: 
    # step 1: checkout the repo code
    - name: Checkout Code
      uses: actions/checkout@v3

    # step 2: log into dockerhub
    - name: Log in to Docker Hub
      uses: docker/login-action@v2  # official docker login action
      with: 
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    # step 3: install docker compose 
    - name: Install Docker compose
      run: |
        sudo apt-get update
        sudo apt-get install -y docker-compose

    # step 4: build and push docker image on dockerhub
    - name: Build and Push Docker image
      run: |
        docker-compose -f docker-compose.yml build
        docker-compose -f docker-compose.yml push 

    # step 5: deploy the applicaton on the ec2 instance
    - name: Deploy to EC2 
      uses: appleboy/ssh-action@v0.1.7
      with:
        host: ${{secrets.EC2_HOST}}
        username: ${{secrets.EC2_USER}}
        key: ${{secrets.EC2_SSH_PRIVATE_KEY}}
        script: |
          cd ~/test
          docker-compose pull
          docker-compose down 
          docker-compose up -d
          
          
